#!/usr/bin/env python3
"""FABLE-020 — write supabase/tower_seed.sql from content/tower/floor_*.json.

    python3 tools/tower/tower_seed.py      # then paste supabase/tower_seed.sql into the SQL editor

Upserts every floor's definition/title/theme/threshold. Retuning a live floor
= edit the author script, re-run it, re-run this, paste. Players pick up the
new definition next time they open the floor — no app update. Floor 1 is
created open; other floors are created locked and are opened only by
record_tower_boss_clear (never re-locked by this script).
"""
import json, glob, os
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

def q(s):  # SQL string literal
    return "'" + s.replace("'", "''") + "'"

lines = ["-- GENERATED by tools/tower/tower_seed.py — do not edit by hand.",
         "-- Run after world_tower_coop.sql. Safe to re-run."]
for path in sorted(glob.glob(os.path.join(ROOT, "content", "tower", "floor_*.json"))):
    f = json.load(open(path))
    lines.append(
        "insert into public.tower_floors (floor, version, title, theme, definition, unlock_threshold, is_open, opened_at) values ("
        f"{f['floor']}, {f.get('version', 1)}, {q(f['title'])}, {q(f.get('theme', ''))}, {q(json.dumps(f, ensure_ascii=False))}::jsonb, "
        f"{f.get('unlock_threshold', 100)}, {'true' if f['floor'] == 1 else 'false'}, {'now()' if f['floor'] == 1 else 'null'})\n"
        "on conflict (floor) do update set version = excluded.version, title = excluded.title, theme = excluded.theme,\n"
        "  definition = excluded.definition, unlock_threshold = excluded.unlock_threshold;")
out = os.path.join(ROOT, "supabase", "tower_seed.sql")
open(out, "w").write("\n".join(lines) + "\n")
print(f"wrote {out} ({len(lines) - 2} floor(s))")
